spring:
  ai:
    dashscope:
      api-key: sk-1f612002f98343a6891a6bf27100b282
      embedding:
        options:
          model: text-embedding-v4
    deepseek:
        api-key: sk-ece64b17333940239252dcf326f3895e
    vectorstore:
      chroma:
        client:
          host: http://121.43.231.155
          port: 8000
        collection-name: douya

feishu:
  app-id: cli_a9b893b544381cb2
  app-secret: StlKaIG84tfKSSowPsYTIdSH05oHlY4t
