spring:
  ai:
    dashscope:
      api-key: api-key
      embedding:
        options:
          model: text-embedding-v4
    deepseek:
        api-key: api-key
    vectorstore:
      chroma:
        client:
          host: http://121.43.231.155
          port: 8000
        collection-name: douya

feishu:
  app-id: app-id
  app-secret: app-secret
